language: python
python:
    - "2.7"
install:
    - pip install --upgrade pip setuptools wheel
    - pip install numpy matplotlib
    - python setup.py install

script:
    - python test/test.py -setup_instrument setup_instrument.ini
